// Mock данные для демонстрации UI
// ⚠️ Бизнес-логика: НЕ ИЗМЕНЯТЬ структуру данных

import type { Station, ChargingSession, User, Tariff, Notification, Statistics, StationElectrical, StationTemperature, StationStats } from '@/types';

const defaultElectrical: StationElectrical = {
  voltagePhase1: 228,
  voltagePhase2: 230,
  voltagePhase3: 229,
  phases: 3,
  maxCurrentA: 16,
  relayState: 'on',
};

const defaultTemperature: StationTemperature = {
  inputContacts: 32,
  port0: 28,
  port1: 27,
  internal: 35,
};

const defaultStats: StationStats = {
  energyTodayKwh: 38.8,
  sessionsToday: 2,
  totalSessions: 1159,
  totalEnergyKwh: 11797,
  totalHours: 10715,
};

export const mockUser: User = {
  id: '1',
  email: 'user@example.com',
  name: 'Иван Петров',
  role: 'individual',
  phone: '+7 999 123-45-67',
  createdAt: '2024-01-15T10:00:00Z',
};

export const mockBusinessUser: User = {
  id: '2',
  email: 'business@company.ru',
  name: 'ООО Заряд Плюс',
  role: 'business',
  organizationId: 'org-1',
  createdAt: '2024-01-01T10:00:00Z',
};

export const mockStations: Station[] = [
  {
    id: 'st-1',
    name: 'ЭЗС Москва-Сити',
    address: 'Пресненская наб., 12',
    latitude: 55.749,
    longitude: 37.537,
    status: 'available',
    ownerId: '1',
    createdAt: '2024-01-10T10:00:00Z',
    connectors: [
      { id: 'c-1', stationId: 'st-1', type: 'Type2', powerKw: 22, status: 'available' },
      { id: 'c-2', stationId: 'st-1', type: 'CCS', powerKw: 50, status: 'available' },
    ],
    electrical: { ...defaultElectrical },
    temperature: { ...defaultTemperature },
    stats: { ...defaultStats, energyTodayKwh: 42.1, sessionsToday: 3 },
  },
  {
    id: 'st-2',
    name: 'ЭЗС ТЦ Европейский',
    address: 'пл. Киевского Вокзала, 2',
    latitude: 55.743,
    longitude: 37.566,
    status: 'charging',
    ownerId: '2',
    organizationId: 'org-1',
    createdAt: '2024-02-01T10:00:00Z',
    connectors: [
      { id: 'c-3', stationId: 'st-2', type: 'Type2', powerKw: 11, status: 'charging' },
      { id: 'c-4', stationId: 'st-2', type: 'CHAdeMO', powerKw: 50, status: 'available' },
    ],
    electrical: { ...defaultElectrical, voltagePhase1: 231 },
    temperature: { ...defaultTemperature, port0: 41, internal: 38 },
    stats: { ...defaultStats, energyTodayKwh: 28.5, sessionsToday: 1, totalSessions: 870 },
  },
  {
    id: 'st-3',
    name: 'ЭЗС Парк Горького',
    address: 'ул. Крымский Вал, 9',
    latitude: 55.731,
    longitude: 37.601,
    status: 'offline',
    ownerId: '2',
    organizationId: 'org-1',
    createdAt: '2024-02-15T10:00:00Z',
    connectors: [
      { id: 'c-5', stationId: 'st-3', type: 'GB/T', powerKw: 60, status: 'offline' },
    ],
    electrical: { ...defaultElectrical, relayState: 'off' },
    temperature: { ...defaultTemperature, inputContacts: 22, port0: 20, internal: 23 },
    stats: { ...defaultStats, energyTodayKwh: 0, sessionsToday: 0, totalSessions: 540 },
  },
  {
    id: 'st-4',
    name: 'ЭЗС ВДНХ',
    address: 'просп. Мира, 119',
    latitude: 55.826,
    longitude: 37.637,
    status: 'available',
    ownerId: '1',
    createdAt: '2024-03-01T10:00:00Z',
    connectors: [
      { id: 'c-6', stationId: 'st-4', type: 'Type2', powerKw: 22, status: 'available' },
      { id: 'c-7', stationId: 'st-4', type: 'CCS', powerKw: 150, status: 'available' },
    ],
    electrical: { ...defaultElectrical },
    temperature: { ...defaultTemperature },
    stats: { ...defaultStats, totalSessions: 2100, totalEnergyKwh: 21500 },
  },
  {
    id: 'st-5',
    name: 'ЭЗС Лужники',
    address: 'ул. Лужники, 24',
    latitude: 55.716,
    longitude: 37.554,
    status: 'available',
    ownerId: '1',
    createdAt: '2024-03-10T10:00:00Z',
    connectors: [
      { id: 'c-8', stationId: 'st-5', type: 'Type2', powerKw: 22, status: 'available' },
    ],
    electrical: { ...defaultElectrical },
    temperature: { ...defaultTemperature },
    stats: { ...defaultStats, sessionsToday: 1, energyTodayKwh: 15.2 },
  },
  {
    id: 'st-6',
    name: 'ЭЗС Арбат',
    address: 'ул. Арбат, 10',
    latitude: 55.752,
    longitude: 37.594,
    status: 'charging',
    ownerId: '1',
    createdAt: '2024-03-15T10:00:00Z',
    connectors: [
      { id: 'c-9', stationId: 'st-6', type: 'CCS', powerKw: 100, status: 'charging' },
    ],
    electrical: { ...defaultElectrical, voltagePhase2: 227 },
    temperature: { ...defaultTemperature, port0: 39, internal: 37 },
    stats: { ...defaultStats, energyTodayKwh: 55.0, sessionsToday: 4, totalSessions: 1580 },
  },
  {
    id: 'st-7',
    name: 'ЭЗС Сокольники',
    address: 'ул. Сокольнический Вал, 1',
    latitude: 55.789,
    longitude: 37.679,
    status: 'available',
    ownerId: '1',
    createdAt: '2024-04-01T10:00:00Z',
    connectors: [
      { id: 'c-10', stationId: 'st-7', type: 'Type2', powerKw: 11, status: 'available' },
      { id: 'c-11', stationId: 'st-7', type: 'CHAdeMO', powerKw: 50, status: 'available' },
    ],
    electrical: { ...defaultElectrical },
    temperature: { ...defaultTemperature },
    stats: { ...defaultStats, totalSessions: 790 },
  },
  {
    id: 'st-8',
    name: 'ЭЗС Измайлово',
    address: 'Измайловское шоссе, 71',
    latitude: 55.794,
    longitude: 37.748,
    status: 'offline',
    ownerId: '1',
    createdAt: '2024-04-10T10:00:00Z',
    connectors: [
      { id: 'c-12', stationId: 'st-8', type: 'GB/T', powerKw: 60, status: 'offline' },
    ],
    electrical: { ...defaultElectrical, relayState: 'off' },
    temperature: { ...defaultTemperature, inputContacts: 21, internal: 22 },
    stats: { ...defaultStats, energyTodayKwh: 0, sessionsToday: 0, totalSessions: 320 },
  },
  {
    id: 'st-9',
    name: 'ЭЗС Коломенское',
    address: 'просп. Андропова, 39',
    latitude: 55.667,
    longitude: 37.671,
    status: 'available',
    ownerId: '1',
    createdAt: '2024-04-20T10:00:00Z',
    connectors: [
      { id: 'c-13', stationId: 'st-9', type: 'Type2', powerKw: 22, status: 'available' },
      { id: 'c-14', stationId: 'st-9', type: 'CCS', powerKw: 150, status: 'available' },
    ],
    electrical: { ...defaultElectrical },
    temperature: { ...defaultTemperature },
    stats: { ...defaultStats, totalSessions: 950, totalEnergyKwh: 9800 },
  },
  {
    id: 'st-10',
    name: 'ЭЗС Останкино',
    address: 'ул. Академика Королева, 15',
    latitude: 55.820,
    longitude: 37.612,
    status: 'available',
    ownerId: '1',
    createdAt: '2024-05-01T10:00:00Z',
    connectors: [
      { id: 'c-15', stationId: 'st-10', type: 'Type2', powerKw: 22, status: 'available' },
    ],
    electrical: { ...defaultElectrical },
    temperature: { ...defaultTemperature },
    stats: { ...defaultStats, totalSessions: 410, totalEnergyKwh: 4200 },
  },
];

export const mockSessions: ChargingSession[] = [
  {
    id: 'ses-1',
    stationId: 'st-1',
    connectorId: 'c-1',
    userId: '1',
    startTime: '2024-06-04T12:45:00Z',
    endTime: '2024-06-04T14:30:00Z',
    energyKwh: 35,
    cost: 490,
    status: 'completed',
  },
  {
    id: 'ses-active-1',
    stationId: 'st-2',
    connectorId: 'c-3',
    userId: '1',
    startTime: new Date(Date.now() - 4 * 60 * 60 * 1000 - 34 * 60 * 1000).toISOString(),
    energyKwh: 28,
    cost: 392,
    status: 'active',
  },
  {
    id: 'ses-active-2',
    stationId: 'st-6',
    connectorId: 'c-9',
    userId: '1',
    startTime: new Date(Date.now() - 1 * 60 * 60 * 1000 - 15 * 60 * 1000).toISOString(),
    energyKwh: 12,
    cost: 168,
    status: 'active',
  },
  {
    id: 'ses-active-3',
    stationId: 'st-1',
    connectorId: 'c-2',
    userId: '1',
    startTime: new Date(Date.now() - 2 * 60 * 60 * 1000 - 45 * 60 * 1000).toISOString(),
    energyKwh: 38,
    cost: 532,
    status: 'active',
  },
  {
    id: 'ses-active-4',
    stationId: 'st-4',
    connectorId: 'c-7',
    userId: '1',
    startTime: new Date(Date.now() - 3 * 60 * 60 * 1000 - 10 * 60 * 1000).toISOString(),
    energyKwh: 45,
    cost: 630,
    status: 'active',
  },
  {
    id: 'ses-active-5',
    stationId: 'st-5',
    connectorId: 'c-8',
    userId: '1',
    startTime: new Date(Date.now() - 0 * 60 * 60 * 1000 - 42 * 60 * 1000).toISOString(),
    energyKwh: 8,
    cost: 112,
    status: 'active',
  },
  {
    id: 'ses-3',
    stationId: 'st-4',
    connectorId: 'c-7',
    userId: '1',
    startTime: '2024-06-03T09:00:00Z',
    endTime: '2024-06-03T09:45:00Z',
    energyKwh: 50,
    cost: 750,
    status: 'completed',
  },
];

export const mockTariffs: Tariff[] = [
  {
    id: 'tar-1',
    organizationId: 'org-1',
    name: 'Стандартный',
    pricePerKwh: 14,
    currency: 'RUB',
    isActive: true,
    createdAt: '2024-01-01T10:00:00Z',
  },
  {
    id: 'tar-2',
    organizationId: 'org-1',
    name: 'Ночной',
    pricePerKwh: 8,
    currency: 'RUB',
    isActive: true,
    createdAt: '2024-01-01T10:00:00Z',
  },
  {
    id: 'tar-3',
    stationId: 'st-2',
    name: 'Премиум быстрая зарядка',
    pricePerKwh: 18,
    currency: 'RUB',
    isActive: true,
    createdAt: '2024-02-01T10:00:00Z',
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'not-1',
    userId: '1',
    title: 'Оплата была успешно обработана',
    message: 'Ваша недавняя оплата за сеанс зарядки была успешно обработана. 4 июня 2024 года ваша оплата в размере 14,00 долларов США за сеанс зарядки на станции EV Station Central Park, слот № 5, была успешно списана с вашей карты Visa, заканчивающейся на 1234.',
    type: 'success',
    isRead: false,
    createdAt: '2024-06-04T13:40:00Z',
  },
  {
    id: 'not-2',
    userId: '1',
    title: 'Расстояние до зарядной станции',
    message: 'Зарядная станция GreenFlow находится в 3 км от вашего местоположения.',
    type: 'info',
    isRead: true,
    createdAt: '2024-06-04T17:42:00Z',
  },
  {
    id: 'not-3',
    userId: '1',
    title: 'Зарядка прошла успешно!',
    message: '4 июня 2024 года в 12:45 ваш автомобиль успешно завершил зарядку на станции EV Station Central Park, слот № 5. Во время этой сессии ваш автомобиль потреблял 35 кВт·ч энергии, повысив уровень заряда аккумулятора с 20 % до 90 %.',
    type: 'success',
    isRead: false,
    createdAt: '2024-06-04T19:40:00Z',
  },
];

export const mockStatistics: Statistics = {
  totalSessions: 86,
  totalEnergyKwh: 1735,
  totalRevenue: 24290,
  activeStations: 3,
  averageSessionDuration: 65,
};
